# Generated by Django 5.0.6 on 2024-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0002_log_delete_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="owner",
            new_name="user_name",
        ),
    ]
