# Generated by Django 5.0.6 on 2024-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0003_rename_owner_log_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="user_name",
            new_name="user",
        ),
    ]
