# Generated by Django 5.0.6 on 2024-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0004_rename_user_name_log_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="answer",
            field=models.CharField(max_length=255, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_right",
            field=models.CharField(max_length=255, verbose_name="Правильный ответ"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_wrong_1",
            field=models.CharField(max_length=255, verbose_name="Неправильный ответ 1"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_wrong_2",
            field=models.CharField(max_length=255, verbose_name="Неправильный ответ 2"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_wrong_3",
            field=models.CharField(max_length=255, verbose_name="Неправильный ответ 3"),
        ),
    ]
